examples/demo/src/demo.rs, examples/demo/src/main.rs, examples/demo/src/perf.rs, src/ffi.rs, src/lib.rs
I modified it so as to pass through compilation in Rust 1.7.0, and removed some warnings.
=> fix nanovg-rs for Rust 1.7.0

examples/demo/src/main.rs
Fix for error:
```rust
error[E0308]: mismatched types
--> src/main.rs:84:25
|
84 | 	glfw.set_swap_interval(0);
| 	                       ^ expected enum `glfw::SwapInterval`, found integral variable
|
= note: expected type `glfw::SwapInterval`
= note:    found type `{integer}`
```
=> Make example work with latest glfw

examples/demo-sdl/src/main.rs
It loaded the GL addresses before creating the GL context, which made it crash at least on OSX.
Use timer.ticks() instead of unsafe methods which had moved.
Also https://github.com/KevinKelley/nanovg-rs/pull/27 is needed to make it run on OSX. After those fixes it ran smoothly.
=> Fix SDL example

src/lib.rs
This adds Solidity enum so it can be used alongside Direction enum as winding. 
This also changes how winding function in SubPath is used:
Instead of:
```
use nanovg::{Direction};
...
sub_path.winding(Direction::Clockwise); // or Direction::CounterClockwise
```
you can use:
```
use nanovg::{Winding, Direction, Solidity};
...
sub_path.winding(Winding::direction(Direction::Clockwise)) // or Direction::CounterClockwise
sub_path.winding(Winding::solidity(Solidity::Hole))        // or Solidity::Solid
```
Direction and Solidity enums are identical in functionality but they are there to be used in different contexts where they mean different things.
=> Add Solidity enum

src/lib.rs
This changes Winding struct from #34 to enum, so it is similar to usage of other enums in library such as ColoringStyle. 
In the end, the only thing that changes is the capitalization, so instead of using Winding::direction(Direction::Clockwise), you use Winding::Direction(Direction::Clockwise).
I think using enum is also more clear than using a struct in this case.
=> Change Winding to be enum instead of struct

src/lib.rs
This PR adds missing line caps and line join options to `StrokeStyle` when drawing stroke.
=> Add missing line options

src/ffi.rs, src/lib.rs
Adds missing text_glyph_positions function for calculating all glyph position in given text.
The function is implemented as iterator over all glyphs.
=> Add text_glyph_positions function

src/lib.rs
Adds missing Clone and Copy traits to TextBounds struct.
Makes fields of TextBounds visible.
=> Fix TextBounds struct field visibility and traits

src/lib.rs
This PR adds missing text_break_lines function.
The function is implemented as iterator over all lines in given text as opposed to c version where you would pass fixed length of text rows to this function.
=> Add text_break_lines function

src/lib.rs
This removes duplicate break_row_width parameter that was already present in TextOptions from text_box_bounds function.
=> Remove duplicate parameter from text_box_bounds

examples/demo-ui.rs, src/lib.rs
Fixes KevinKelley/nanovg-rs#45
We can now create rectangles, circles and other objects in subpaths. 
This does not break existing code.
=> Fix subpath usability

examples/demo-clock.rs, examples/demo-glutin.rs, examples/demo-ui.rs, src/lib.rs
Matrix functions now changes and premultiplies previous matrix, so we can accumulate calls to Transform.
It is for example possible to translate then rotate and then translate again, making this approach more flexible. This also means that the order in which methods on Transform are called, matters. The setters are still there and are renamed to with_* methods so you can construct Transform with specified values. Every call clones previous Transform as it is with setter methods, so immutability is preserved. It is implemented by using underlying nanovg functions.
=> Improve matrix functions

examples/demo-clock.rs, examples/demo-glutin.rs, examples/demo-ui.rs, src/lib.rs
Paints do not need nanovg context passed to them because underlying nanovg library does not use it. I believe this was done in c api of nanovg to be consistent throughout the library, we do not need to do that, because we have special constructors for paints. 
You can see the NVG_NOTUSED starting in paint functions [here](https://github.com/memononen/nanovg/blob/e70a78e42e781bc73393afe47a62e6c049197a0b/src/nanovg.c#L842).
=> Simplify the creation of paints

examples/demo-clock.rs, examples/demo-cutout.rs, examples/demo-glutin.rs, examples/demo-ui.rs, src/lib.rs
I removed Frame for drawing paths and put path function into Context struct to be more in line with the c api of nanovg, but I wanted some feedback, because I don't know if this is the right way.
What was my intention with this, is when you have function for drawing some composite shape or widget, I wanted it to be more straightforward.
Example:
I wanted this:
```
fn button(context: &Context, ......) {
context.path(|path| {
path.rect(...);
});
context.text(...);
}
```
Instead of this:
```
fn button(frame: &Frame, ......) {
frame.path(|path| {
path.rect(...);
});
frame.context().text(...);
}
```
What I don't like here is the indirection.
I considered putting everything into Frame and keeping only .frame function in Context, but then I looked at the c-api and saw that everything takes …
=> Remove frame, use context for every drawing

examples/demo-clock.rs, examples/demo-cutout.rs, examples/demo-glutin.rs, examples/demo-ui.rs, src/lib.rs
This moves text drawing to frame and reverts #55. I have text functions using transforms ready, wanted to make this change first. I will rebase text transforms on master when this gets merged and create another PR for them.
=> Move text drawing to frame

Cargo.toml
Specifies libc version to 0.2.
Closes #51
=> Specify libc version

Cargo.toml, src/ffi.rs, src/lib.rs
libc dependency is not needed, we use it only for c types aliases, and they are also defined in the standard library, so we use that instead of libc
=> Remove libc dependency

examples/demo-text.rs, examples/demo-ui.rs, src/lib.rs
We can use .peekable() on TextGlyphPositions iterator to get the next
glyph if we want to, no need to store additional field for this purpose.
The only disadvantage is, that we have to use while loop instead of for loop, but I think, this is more clear and clarifies the usage and those who don't need .next are not confused.
Closes #68
=> Remove GlyphPosition's next field in favor of .peekable()

Cargo.toml, nanovg-sys/Cargo.toml
Referencing #56.
The linking error was caused by `nanovg-sys` being always built with `gl3`. The way feature selection works is that default features are always on unless explicitly turned off. In other words if I said:
```toml
nanovg-sys = { path = "nanovg-sys", features = ["gl2"]}
```
then because `nanovg-sys` defaults to:
```toml
default = ["gl3"]
```
the enabled features would be `gl3` and `gl2`. Now, because `build.rs` checks for `gl3` first, it would build with `gl3`. Hence the linking error.
As you said `nanovg-sys` won't build without a default feature so I gave it one and then disabled it in `nanovg-rs`. This works because `cargo publish` does not publish the binaries. It runs the clean build only as a validation check (afaik).
I also removed the default feature from `nanovg-rs` …
=> Fix cargo publish; fix linking errors when using backends other than GL3

Cargo.toml, nanovg-sys/Cargo.toml
Looks like docs.rs needs to successfully build to generate the docs and since we no longer specify the default backend it fails: https://docs.rs/crate/nanovg/1.0.0
I added the required docs.rs-specific configuration to both crates so we aren't left doc-less 👿 (based on https://docs.rs/about).
#56
=> Fix docs on docs.rs

nanovg-sys/lib.rs, src/lib.rs
Besides `Alignment`, I also added Eq/PartialEq to a lot of other types for which it might make sense to have these.
=> Derive PartialEq and Eq for various types. Fixes #75.
